version: "3"

services:
  tidal-dl:
    container_name: tidal-local
    image: local/tidal-local
    ports:
      - "8885:80"
    volumes:
      - 'C:\Users\rgnet\Music\download:/production/www/cgi-bin/download/'
      - 'C:\Users\rgnet\Documents\github\tidal-dl-wrapper\tmp\:/production/www/cgi-bin/configuration/'
