# This is a basic workflow to help you get started with Actions

name: Push Readme Update to Docker Hub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - README.md

jobs:
  dockerHubPush:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Update README
        uses: peter-evans/dockerhub-description@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACTUAL_PASSWORD }}
          repository: rgnet1/tidal-dl
