name: Build and Push - Development

on:
  push:
    branches:
      - development
      - layer-minimization
    paths-ignore:
      - '**/README.md'
      - '**.yml'

jobs:
  Docker-Build-Developmnet:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        id: buildx
        uses: docker/setup-qemu-action@v1
        with:
          version: latest

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: true
          tags: rgnet1/tidal-dl:development