name: Build

on:
  push:
    branches: main
    paths-ignore:
      - '**/README.md'
      - '**.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Set up QEMU
        id: buildx
        uses: docker/setup-qemu-action@v1
        with:
          version: latest
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_ACTUAL_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build \
            --tag rgnet1/tidal-dl:latest \
            --platform linux/amd64,linux/arm/v7,linux/arm64 --push .